// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSD3_9ek13HRRQipjUGg_bUWd59XpgYTU',
    appId: '1:352750908129:web:81b9627eb5a29093affda0',
    messagingSenderId: '352750908129',
    projectId: 'beestore-app',
    authDomain: 'beestore-app.firebaseapp.com',
    storageBucket: 'beestore-app.appspot.com',
    measurementId: 'G-7Y22TKBN9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zdU1OBPIV2lrUCrVewU5yH2vGfqCmlg',
    appId: '1:352750908129:android:0d93a39c135d69edaffda0',
    messagingSenderId: '352750908129',
    projectId: 'beestore-app',
    storageBucket: 'beestore-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ27yCzKNG1-LUzIfTEIDIzMK915EIFRw',
    appId: '1:352750908129:ios:2815544fb611111faffda0',
    messagingSenderId: '352750908129',
    projectId: 'beestore-app',
    storageBucket: 'beestore-app.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ27yCzKNG1-LUzIfTEIDIzMK915EIFRw',
    appId: '1:352750908129:ios:ba6b89f0b43c65a3affda0',
    messagingSenderId: '352750908129',
    projectId: 'beestore-app',
    storageBucket: 'beestore-app.appspot.com',
    iosBundleId: 'com.example.beeStore.RunnerTests',
  );
}
